# Automatically build the default branch then release with tag "aurora" and marked as pre-release.

name: Build and Release

on:
  push:
    branches:
      - trunk

jobs:
  validate:
    name: Validating Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Install
        run: yarn install --frozen-lockfile && yarn playwright install
      - name: Build
        run: yarn run build
      - name: Test
        run: yarn run test
      - name: Upload Canary Userscript
        uses: actions/upload-artifact@v4
        with:
          name: Aurora - ${{ matrix.runs-on }}
          path: dist/eureka.user.js
          overwrite: true
      - name: Create Nightly Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "aurora"
          prerelease: true
          title: "Aurora"
          files: |
            dist/eureka.user.js
